# Generated by Django 4.2.14 on 2024-08-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_delete_videoproxy_videopublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'DRAFT')], default='DR', max_length=2),
        ),
    ]
