# Generated by Django 4.2.14 on 2024-08-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_timestamp_video_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
